// This file is auto-generated by @hey-api/openapi-ts

export const Body_login_login_access_tokenSchema = {
    properties: {
        grant_type: {
            anyOf: [
                {
                    type: 'string',
                    pattern: 'password'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Grant Type'
        },
        username: {
            type: 'string',
            title: 'Username'
        },
        password: {
            type: 'string',
            title: 'Password'
        },
        scope: {
            type: 'string',
            title: 'Scope',
            default: ''
        },
        client_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Id'
        },
        client_secret: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Secret'
        }
    },
    type: 'object',
    required: ['username', 'password'],
    title: 'Body_login-login_access_token'
} as const;

export const CardGameAnswerCreateSchema = {
    properties: {
        card_index: {
            type: 'integer',
            title: 'Card Index'
        },
        selected_answers: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Selected Answers'
        }
    },
    type: 'object',
    required: ['card_index', 'selected_answers'],
    title: 'CardGameAnswerCreate'
} as const;

export const CardGameAnswerResponseSchema = {
    properties: {
        is_correct: {
            type: 'boolean',
            title: 'Is Correct'
        },
        effect_value: {
            type: 'integer',
            title: 'Effect Value'
        },
        card_type: {
            type: 'string',
            title: 'Card Type'
        },
        target_health: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Target Health'
        },
        target_shield: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Target Shield'
        }
    },
    type: 'object',
    required: ['is_correct', 'effect_value', 'card_type'],
    title: 'CardGameAnswerResponse'
} as const;

export const CardGameCreateResponseSchema = {
    properties: {
        room_code: {
            type: 'string',
            title: 'Room Code'
        },
        game_id: {
            type: 'string',
            title: 'Game Id'
        },
        subjects: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Subjects'
        },
        topics: {
            anyOf: [
                {
                    items: {
                        type: 'string'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Topics'
        }
    },
    type: 'object',
    required: ['room_code', 'game_id', 'subjects'],
    title: 'CardGameCreateResponse'
} as const;

export const CardGameJoinResponseSchema = {
    properties: {
        game_id: {
            type: 'string',
            title: 'Game Id'
        },
        host_name: {
            type: 'string',
            title: 'Host Name'
        },
        status: {
            type: 'string',
            title: 'Status'
        },
        subjects: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Subjects'
        },
        topics: {
            anyOf: [
                {
                    items: {
                        type: 'string'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Topics'
        }
    },
    type: 'object',
    required: ['game_id', 'host_name', 'status', 'subjects'],
    title: 'CardGameJoinResponse'
} as const;

export const CardGamePlayerStateSchema = {
    properties: {
        id: {
            type: 'string',
            title: 'Id'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        health: {
            type: 'integer',
            title: 'Health'
        },
        shield: {
            type: 'integer',
            title: 'Shield'
        },
        hand_count: {
            type: 'integer',
            title: 'Hand Count'
        },
        is_current_turn: {
            type: 'boolean',
            title: 'Is Current Turn'
        }
    },
    type: 'object',
    required: ['id', 'name', 'health', 'shield', 'hand_count', 'is_current_turn'],
    title: 'CardGamePlayerState'
} as const;

export const CardGameResultsResponseSchema = {
    properties: {
        game_id: {
            type: 'string',
            title: 'Game Id'
        },
        status: {
            type: 'string',
            title: 'Status'
        },
        winner: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Winner'
        },
        end_reason: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'End Reason'
        },
        host: {
            '$ref': '#/components/schemas/CardGamePlayerState'
        },
        guest: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/CardGamePlayerState'
                },
                {
                    type: 'null'
                }
            ]
        },
        total_turns: {
            type: 'integer',
            title: 'Total Turns'
        }
    },
    type: 'object',
    required: ['game_id', 'status', 'winner', 'end_reason', 'host', 'guest', 'total_turns'],
    title: 'CardGameResultsResponse'
} as const;

export const CardGameSessionCreateSchema = {
    properties: {
        subjects: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Subjects'
        },
        topics: {
            anyOf: [
                {
                    items: {
                        type: 'string'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Topics'
        }
    },
    type: 'object',
    required: ['subjects'],
    title: 'CardGameSessionCreate'
} as const;

export const CardGameSessionWithPlayersSchema = {
    properties: {
        room_code: {
            type: 'string',
            maxLength: 6,
            title: 'Room Code'
        },
        subjects: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Subjects'
        },
        topics: {
            anyOf: [
                {
                    items: {
                        type: 'string'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Topics'
        },
        status: {
            type: 'string',
            maxLength: 20,
            title: 'Status',
            default: 'waiting'
        },
        host_ready: {
            type: 'boolean',
            title: 'Host Ready',
            default: false
        },
        guest_ready: {
            type: 'boolean',
            title: 'Guest Ready',
            default: false
        },
        host_health: {
            type: 'integer',
            title: 'Host Health',
            default: 10
        },
        guest_health: {
            type: 'integer',
            title: 'Guest Health',
            default: 10
        },
        host_shield: {
            type: 'integer',
            title: 'Host Shield',
            default: 0
        },
        guest_shield: {
            type: 'integer',
            title: 'Guest Shield',
            default: 0
        },
        max_health: {
            type: 'integer',
            title: 'Max Health',
            default: 30
        },
        host_hand: {
            items: {
                additionalProperties: true,
                type: 'object'
            },
            type: 'array',
            title: 'Host Hand'
        },
        guest_hand: {
            items: {
                additionalProperties: true,
                type: 'object'
            },
            type: 'array',
            title: 'Guest Hand'
        },
        deck: {
            items: {
                additionalProperties: true,
                type: 'object'
            },
            type: 'array',
            title: 'Deck'
        },
        discard_pile: {
            items: {
                additionalProperties: true,
                type: 'object'
            },
            type: 'array',
            title: 'Discard Pile'
        },
        current_turn: {
            type: 'string',
            maxLength: 10,
            title: 'Current Turn',
            default: 'host'
        },
        turn_number: {
            type: 'integer',
            title: 'Turn Number',
            default: 0
        },
        fatigue_damage: {
            type: 'integer',
            title: 'Fatigue Damage',
            default: 0
        },
        winner: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 10
                },
                {
                    type: 'null'
                }
            ],
            title: 'Winner'
        },
        end_reason: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 20
                },
                {
                    type: 'null'
                }
            ],
            title: 'End Reason'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        host_id: {
            type: 'string',
            format: 'uuid',
            title: 'Host Id'
        },
        guest_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Guest Id'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        started_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Started At'
        },
        completed_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Completed At'
        },
        host_name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Host Name'
        },
        guest_name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Guest Name'
        }
    },
    type: 'object',
    required: ['room_code', 'subjects', 'id', 'host_id', 'guest_id', 'created_at', 'started_at', 'completed_at'],
    title: 'CardGameSessionWithPlayers'
} as const;

export const CardGameStatePublicSchema = {
    properties: {
        game_id: {
            type: 'string',
            title: 'Game Id'
        },
        status: {
            type: 'string',
            title: 'Status'
        },
        host: {
            '$ref': '#/components/schemas/CardGamePlayerState'
        },
        guest: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/CardGamePlayerState'
                },
                {
                    type: 'null'
                }
            ]
        },
        deck_count: {
            type: 'integer',
            title: 'Deck Count'
        },
        turn_number: {
            type: 'integer',
            title: 'Turn Number'
        },
        fatigue_damage: {
            type: 'integer',
            title: 'Fatigue Damage'
        },
        current_turn: {
            type: 'string',
            title: 'Current Turn'
        },
        winner: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Winner'
        }
    },
    type: 'object',
    required: ['game_id', 'status', 'host', 'guest', 'deck_count', 'turn_number', 'fatigue_damage', 'current_turn'],
    title: 'CardGameStatePublic'
} as const;

export const FeatureFlagPublicSchema = {
    properties: {
        key: {
            type: 'string',
            maxLength: 100,
            title: 'Key'
        },
        name: {
            type: 'string',
            maxLength: 200,
            title: 'Name'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        enabled: {
            type: 'boolean',
            title: 'Enabled',
            default: false
        },
        enabled_for_roles: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Enabled For Roles',
            default: []
        },
        enabled_for_users: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Enabled For Users',
            default: []
        },
        env_var_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 100
                },
                {
                    type: 'null'
                }
            ],
            title: 'Env Var Name'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At'
        }
    },
    type: 'object',
    required: ['key', 'name', 'id', 'created_at', 'updated_at'],
    title: 'FeatureFlagPublic'
} as const;

export const FeatureFlagUpdateSchema = {
    properties: {
        name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        enabled: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Enabled'
        },
        enabled_for_roles: {
            anyOf: [
                {
                    items: {
                        type: 'string'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Enabled For Roles'
        },
        enabled_for_users: {
            anyOf: [
                {
                    items: {
                        type: 'string'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Enabled For Users'
        }
    },
    type: 'object',
    title: 'FeatureFlagUpdate'
} as const;

export const FeatureFlagsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/FeatureFlagPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'FeatureFlagsPublic'
} as const;

export const GenerateQuestionRequestSchema = {
    properties: {
        template_id: {
            type: 'string',
            format: 'uuid',
            title: 'Template Id'
        },
        num_questions: {
            type: 'integer',
            title: 'Num Questions',
            default: 5
        },
        skip_content_validation: {
            type: 'boolean',
            title: 'Skip Content Validation',
            default: false
        },
        temperature: {
            type: 'number',
            title: 'Temperature',
            default: 0.7
        }
    },
    type: 'object',
    required: ['template_id'],
    title: 'GenerateQuestionRequest',
    description: 'Request model for question generation.'
} as const;

export const GenerateQuestionResponseSchema = {
    properties: {
        batch_id: {
            type: 'string',
            format: 'uuid',
            title: 'Batch Id'
        },
        total_requested: {
            type: 'integer',
            title: 'Total Requested'
        },
        successful: {
            type: 'integer',
            title: 'Successful'
        },
        failed: {
            type: 'integer',
            title: 'Failed'
        },
        questions: {
            items: {
                additionalProperties: true,
                type: 'object'
            },
            type: 'array',
            title: 'Questions'
        }
    },
    type: 'object',
    required: ['batch_id', 'total_requested', 'successful', 'failed', 'questions'],
    title: 'GenerateQuestionResponse',
    description: 'Response model for question generation.'
} as const;

export const GeneratedQuestionPublicSchema = {
    properties: {
        question_data: {
            additionalProperties: true,
            type: 'object',
            title: 'Question Data'
        },
        template_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Template Id'
        },
        batch_id: {
            type: 'string',
            format: 'uuid',
            title: 'Batch Id'
        },
        status: {
            type: 'string',
            maxLength: 20,
            title: 'Status',
            default: 'pending'
        },
        validation_score: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Validation Score'
        },
        validation_feedback: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 1000
                },
                {
                    type: 'null'
                }
            ],
            title: 'Validation Feedback'
        },
        rejection_reason: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Rejection Reason'
        },
        subtopic: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 200
                },
                {
                    type: 'null'
                }
            ],
            title: 'Subtopic'
        },
        question_type: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 100
                },
                {
                    type: 'null'
                }
            ],
            title: 'Question Type'
        },
        diversity_score: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Diversity Score'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        created_by: {
            type: 'string',
            format: 'uuid',
            title: 'Created By'
        },
        generated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Generated At'
        },
        reviewed_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Reviewed At'
        },
        reviewed_by: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Reviewed By'
        }
    },
    type: 'object',
    required: ['question_data', 'batch_id', 'id', 'created_by', 'generated_at', 'reviewed_at', 'reviewed_by'],
    title: 'GeneratedQuestionPublic'
} as const;

export const GeneratedQuestionsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/GeneratedQuestionPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'GeneratedQuestionsPublic'
} as const;

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                '$ref': '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const ItemCreateSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        }
    },
    type: 'object',
    required: ['title'],
    title: 'ItemCreate'
} as const;

export const ItemPublicSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        owner_id: {
            type: 'string',
            format: 'uuid',
            title: 'Owner Id'
        }
    },
    type: 'object',
    required: ['title', 'id', 'owner_id'],
    title: 'ItemPublic'
} as const;

export const ItemUpdateSchema = {
    properties: {
        title: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        }
    },
    type: 'object',
    title: 'ItemUpdate'
} as const;

export const ItemsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/ItemPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'ItemsPublic'
} as const;

export const MessageSchema = {
    properties: {
        message: {
            type: 'string',
            title: 'Message'
        }
    },
    type: 'object',
    required: ['message'],
    title: 'Message'
} as const;

export const NewPasswordSchema = {
    properties: {
        token: {
            type: 'string',
            title: 'Token'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['token', 'new_password'],
    title: 'NewPassword'
} as const;

export const PrivateUserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            title: 'Email'
        },
        password: {
            type: 'string',
            title: 'Password'
        },
        full_name: {
            type: 'string',
            title: 'Full Name'
        },
        is_verified: {
            type: 'boolean',
            title: 'Is Verified',
            default: false
        }
    },
    type: 'object',
    required: ['email', 'password', 'full_name'],
    title: 'PrivateUserCreate'
} as const;

export const QuestionCreateSchema = {
    properties: {
        question_text: {
            type: 'string',
            maxLength: 10000,
            minLength: 1,
            title: 'Question Text'
        },
        choices: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Choices'
        },
        correct_answers: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Correct Answers'
        },
        subject: {
            type: 'string',
            maxLength: 100,
            minLength: 1,
            title: 'Subject'
        },
        topic: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 100
                },
                {
                    type: 'null'
                }
            ],
            title: 'Topic'
        }
    },
    type: 'object',
    required: ['question_text', 'choices', 'correct_answers', 'subject'],
    title: 'QuestionCreate'
} as const;

export const QuestionPublicSchema = {
    properties: {
        question_text: {
            type: 'string',
            maxLength: 10000,
            minLength: 1,
            title: 'Question Text'
        },
        choices: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Choices'
        },
        correct_answers: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Correct Answers'
        },
        subject: {
            type: 'string',
            maxLength: 100,
            minLength: 1,
            title: 'Subject'
        },
        topic: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 100
                },
                {
                    type: 'null'
                }
            ],
            title: 'Topic'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        created_by: {
            type: 'string',
            format: 'uuid',
            title: 'Created By'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At'
        },
        subject_id: {
            type: 'string',
            format: 'uuid',
            title: 'Subject Id'
        },
        topic_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Topic Id'
        }
    },
    type: 'object',
    required: ['question_text', 'choices', 'correct_answers', 'subject', 'id', 'created_by', 'created_at', 'updated_at', 'subject_id', 'topic_id'],
    title: 'QuestionPublic'
} as const;

export const QuestionTemplateCreateSchema = {
    properties: {
        subject: {
            type: 'string',
            maxLength: 100,
            minLength: 1,
            title: 'Subject'
        },
        topic: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 100
                },
                {
                    type: 'null'
                }
            ],
            title: 'Topic'
        },
        difficulty: {
            type: 'string',
            maxLength: 20,
            title: 'Difficulty'
        },
        template_prompt: {
            type: 'string',
            maxLength: 2000,
            minLength: 1,
            title: 'Template Prompt'
        },
        example_questions: {
            items: {
                additionalProperties: true,
                type: 'object'
            },
            type: 'array',
            title: 'Example Questions'
        },
        constraints: {
            additionalProperties: true,
            type: 'object',
            title: 'Constraints'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        }
    },
    type: 'object',
    required: ['subject', 'difficulty', 'template_prompt', 'example_questions'],
    title: 'QuestionTemplateCreate'
} as const;

export const QuestionTemplatePublicSchema = {
    properties: {
        subject: {
            type: 'string',
            maxLength: 100,
            minLength: 1,
            title: 'Subject'
        },
        topic: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 100
                },
                {
                    type: 'null'
                }
            ],
            title: 'Topic'
        },
        difficulty: {
            type: 'string',
            maxLength: 20,
            title: 'Difficulty'
        },
        template_prompt: {
            type: 'string',
            maxLength: 2000,
            minLength: 1,
            title: 'Template Prompt'
        },
        example_questions: {
            items: {
                additionalProperties: true,
                type: 'object'
            },
            type: 'array',
            title: 'Example Questions'
        },
        constraints: {
            additionalProperties: true,
            type: 'object',
            title: 'Constraints'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        created_by: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created By'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At'
        }
    },
    type: 'object',
    required: ['subject', 'difficulty', 'template_prompt', 'example_questions', 'id', 'created_by', 'created_at', 'updated_at'],
    title: 'QuestionTemplatePublic'
} as const;

export const QuestionTemplateUpdateSchema = {
    properties: {
        subject: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 100,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Subject'
        },
        topic: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 100
                },
                {
                    type: 'null'
                }
            ],
            title: 'Topic'
        },
        difficulty: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 20
                },
                {
                    type: 'null'
                }
            ],
            title: 'Difficulty'
        },
        template_prompt: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 2000,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Template Prompt'
        },
        example_questions: {
            anyOf: [
                {
                    items: {
                        additionalProperties: true,
                        type: 'object'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Example Questions'
        },
        constraints: {
            anyOf: [
                {
                    additionalProperties: true,
                    type: 'object'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Constraints'
        },
        is_active: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Active'
        }
    },
    type: 'object',
    title: 'QuestionTemplateUpdate'
} as const;

export const QuestionTemplatesPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/QuestionTemplatePublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'QuestionTemplatesPublic'
} as const;

export const QuestionUpdateSchema = {
    properties: {
        question_text: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 10000,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Question Text'
        },
        choices: {
            anyOf: [
                {
                    items: {
                        type: 'string'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Choices'
        },
        correct_answers: {
            anyOf: [
                {
                    items: {
                        type: 'string'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Correct Answers'
        },
        subject: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 100,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Subject'
        },
        topic: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 100
                },
                {
                    type: 'null'
                }
            ],
            title: 'Topic'
        }
    },
    type: 'object',
    title: 'QuestionUpdate'
} as const;

export const QuestionsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/QuestionPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'QuestionsPublic'
} as const;

export const QuizAnswerSubmitSchema = {
    properties: {
        question_id: {
            type: 'string',
            title: 'Question Id'
        },
        selected_answers: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Selected Answers'
        }
    },
    type: 'object',
    required: ['question_id', 'selected_answers'],
    title: 'QuizAnswerSubmit'
} as const;

export const QuizAttemptPublicSchema = {
    properties: {
        quiz_id: {
            type: 'string',
            format: 'uuid',
            title: 'Quiz Id'
        },
        user_id: {
            type: 'string',
            format: 'uuid',
            title: 'User Id'
        },
        question_ids: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Question Ids'
        },
        user_answers: {
            additionalProperties: true,
            type: 'object',
            title: 'User Answers'
        },
        score: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Score'
        },
        total_questions: {
            type: 'integer',
            title: 'Total Questions'
        },
        time_taken: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Time Taken'
        },
        started_at: {
            type: 'string',
            format: 'date-time',
            title: 'Started At'
        },
        completed_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Completed At'
        },
        status: {
            type: 'string',
            maxLength: 20,
            title: 'Status',
            default: 'in_progress'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        }
    },
    type: 'object',
    required: ['quiz_id', 'user_id', 'question_ids', 'total_questions', 'started_at', 'id'],
    title: 'QuizAttemptPublic'
} as const;

export const QuizAttemptsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/QuizAttemptPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'QuizAttemptsPublic'
} as const;

export const QuizCreateSchema = {
    properties: {
        subjects: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Subjects'
        },
        topics: {
            anyOf: [
                {
                    items: {
                        type: 'string'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Topics'
        },
        num_questions: {
            type: 'integer',
            maximum: 50,
            minimum: 1,
            title: 'Num Questions',
            default: 5
        },
        time_limit: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Time Limit'
        },
        is_timed: {
            type: 'boolean',
            title: 'Is Timed',
            default: false
        }
    },
    type: 'object',
    required: ['subjects'],
    title: 'QuizCreate'
} as const;

export const QuizPublicSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 200,
            minLength: 1,
            title: 'Title'
        },
        subjects: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Subjects'
        },
        topics: {
            anyOf: [
                {
                    items: {
                        type: 'string'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Topics'
        },
        num_questions: {
            type: 'integer',
            maximum: 50,
            minimum: 1,
            title: 'Num Questions',
            default: 5
        },
        time_limit: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Time Limit'
        },
        is_timed: {
            type: 'boolean',
            title: 'Is Timed',
            default: false
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        created_by: {
            type: 'string',
            format: 'uuid',
            title: 'Created By'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['title', 'subjects', 'id', 'created_by', 'created_at'],
    title: 'QuizPublic'
} as const;

export const QuizResultDetailSchema = {
    properties: {
        question_id: {
            type: 'string',
            title: 'Question Id'
        },
        question_text: {
            type: 'string',
            title: 'Question Text'
        },
        choices: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Choices'
        },
        correct_answers: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Correct Answers'
        },
        user_answers: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'User Answers'
        },
        is_correct: {
            type: 'boolean',
            title: 'Is Correct'
        },
        subject: {
            type: 'string',
            title: 'Subject'
        },
        topic: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Topic'
        }
    },
    type: 'object',
    required: ['question_id', 'question_text', 'choices', 'correct_answers', 'user_answers', 'is_correct', 'subject', 'topic'],
    title: 'QuizResultDetail'
} as const;

export const QuizResultPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        quiz_id: {
            type: 'string',
            format: 'uuid',
            title: 'Quiz Id'
        },
        score: {
            type: 'integer',
            title: 'Score'
        },
        total_questions: {
            type: 'integer',
            title: 'Total Questions'
        },
        percentage: {
            type: 'number',
            title: 'Percentage'
        },
        time_taken: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Time Taken'
        },
        started_at: {
            type: 'string',
            format: 'date-time',
            title: 'Started At'
        },
        completed_at: {
            type: 'string',
            format: 'date-time',
            title: 'Completed At'
        },
        status: {
            type: 'string',
            title: 'Status'
        },
        details: {
            items: {
                '$ref': '#/components/schemas/QuizResultDetail'
            },
            type: 'array',
            title: 'Details'
        }
    },
    type: 'object',
    required: ['id', 'quiz_id', 'score', 'total_questions', 'percentage', 'time_taken', 'started_at', 'completed_at', 'status', 'details'],
    title: 'QuizResultPublic'
} as const;

export const RejectQuestionRequestSchema = {
    properties: {
        reason: {
            type: 'string',
            title: 'Reason'
        }
    },
    type: 'object',
    required: ['reason'],
    title: 'RejectQuestionRequest',
    description: 'Request model for rejecting a question.'
} as const;

export const SubjectPublicSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 100,
            minLength: 1,
            title: 'Name'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        }
    },
    type: 'object',
    required: ['name', 'id'],
    title: 'SubjectPublic'
} as const;

export const SubjectsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/SubjectPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'SubjectsPublic'
} as const;

export const TokenSchema = {
    properties: {
        access_token: {
            type: 'string',
            title: 'Access Token'
        },
        token_type: {
            type: 'string',
            title: 'Token Type',
            default: 'bearer'
        }
    },
    type: 'object',
    required: ['access_token'],
    title: 'Token'
} as const;

export const TopicPublicSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 100,
            minLength: 1,
            title: 'Name'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        }
    },
    type: 'object',
    required: ['name', 'id'],
    title: 'TopicPublic'
} as const;

export const TopicsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/TopicPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'TopicsPublic'
} as const;

export const UpdatePasswordSchema = {
    properties: {
        current_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Current Password'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['current_password', 'new_password'],
    title: 'UpdatePassword'
} as const;

export const UserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        is_teacher: {
            type: 'boolean',
            title: 'Is Teacher',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserCreate'
} as const;

export const UserPublicSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        is_teacher: {
            type: 'boolean',
            title: 'Is Teacher',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        }
    },
    type: 'object',
    required: ['email', 'id'],
    title: 'UserPublic'
} as const;

export const UserRegisterSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserRegister'
} as const;

export const UserUpdateSchema = {
    properties: {
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        is_teacher: {
            type: 'boolean',
            title: 'Is Teacher',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        password: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 128,
                    minLength: 8
                },
                {
                    type: 'null'
                }
            ],
            title: 'Password'
        }
    },
    type: 'object',
    title: 'UserUpdate'
} as const;

export const UserUpdateMeSchema = {
    properties: {
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        }
    },
    type: 'object',
    title: 'UserUpdateMe'
} as const;

export const UsersPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/UserPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'UsersPublic'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        }
    },
    type: 'object',
    required: ['loc', 'msg', 'type'],
    title: 'ValidationError'
} as const;