// This file is auto-generated by @hey-api/openapi-ts

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type CardGameAnswerCreate = {
    card_index: number;
    selected_answers: Array<(string)>;
};

export type CardGameAnswerResponse = {
    is_correct: boolean;
    effect_value: number;
    card_type: string;
    target_health?: (number | null);
    target_shield?: (number | null);
};

export type CardGameCreateResponse = {
    room_code: string;
    game_id: string;
    subjects: Array<(string)>;
    topics?: (Array<(string)> | null);
};

export type CardGameJoinResponse = {
    game_id: string;
    host_name: string;
    status: string;
    subjects: Array<(string)>;
    topics?: (Array<(string)> | null);
};

export type CardGamePlayerState = {
    id: string;
    name: string;
    health: number;
    shield: number;
    hand_count: number;
    is_current_turn: boolean;
};

export type CardGameResultsResponse = {
    game_id: string;
    status: string;
    winner: (string | null);
    end_reason: (string | null);
    host: CardGamePlayerState;
    guest: (CardGamePlayerState | null);
    total_turns: number;
};

export type CardGameSessionCreate = {
    subjects: Array<(string)>;
    topics?: (Array<(string)> | null);
};

export type CardGameSessionWithPlayers = {
    room_code: string;
    subjects: Array<(string)>;
    topics?: (Array<(string)> | null);
    status?: string;
    host_ready?: boolean;
    guest_ready?: boolean;
    host_health?: number;
    guest_health?: number;
    host_shield?: number;
    guest_shield?: number;
    max_health?: number;
    host_hand?: Array<{
        [key: string]: unknown;
    }>;
    guest_hand?: Array<{
        [key: string]: unknown;
    }>;
    deck?: Array<{
        [key: string]: unknown;
    }>;
    discard_pile?: Array<{
        [key: string]: unknown;
    }>;
    current_turn?: string;
    turn_number?: number;
    fatigue_damage?: number;
    winner?: (string | null);
    end_reason?: (string | null);
    id: string;
    host_id: string;
    guest_id: (string | null);
    created_at: string;
    started_at: (string | null);
    completed_at: (string | null);
    host_name?: (string | null);
    guest_name?: (string | null);
};

export type CardGameStatePublic = {
    game_id: string;
    status: string;
    host: CardGamePlayerState;
    guest: (CardGamePlayerState | null);
    deck_count: number;
    turn_number: number;
    fatigue_damage: number;
    current_turn: string;
    winner?: (string | null);
};

export type FeatureFlagPublic = {
    key: string;
    name: string;
    description?: (string | null);
    enabled?: boolean;
    enabled_for_roles?: Array<(string)>;
    enabled_for_users?: Array<(string)>;
    env_var_name?: (string | null);
    id: string;
    created_at: string;
    updated_at: string;
};

export type FeatureFlagsPublic = {
    data: Array<FeatureFlagPublic>;
    count: number;
};

export type FeatureFlagUpdate = {
    name?: (string | null);
    description?: (string | null);
    enabled?: (boolean | null);
    enabled_for_roles?: (Array<(string)> | null);
    enabled_for_users?: (Array<(string)> | null);
};

export type GeneratedQuestionPublic = {
    question_data: {
        [key: string]: unknown;
    };
    template_id?: (string | null);
    batch_id: string;
    status?: string;
    validation_score?: (number | null);
    validation_feedback?: (string | null);
    rejection_reason?: (string | null);
    subtopic?: (string | null);
    question_type?: (string | null);
    diversity_score?: (number | null);
    id: string;
    created_by: string;
    generated_at: string;
    reviewed_at: (string | null);
    reviewed_by: (string | null);
};

export type GeneratedQuestionsPublic = {
    data: Array<GeneratedQuestionPublic>;
    count: number;
};

/**
 * Request model for question generation.
 */
export type GenerateQuestionRequest = {
    template_id: string;
    num_questions?: number;
    skip_content_validation?: boolean;
    temperature?: number;
};

/**
 * Response model for question generation.
 */
export type GenerateQuestionResponse = {
    batch_id: string;
    total_requested: number;
    successful: number;
    failed: number;
    questions: Array<{
        [key: string]: unknown;
    }>;
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type ItemCreate = {
    title: string;
    description?: (string | null);
};

export type ItemPublic = {
    title: string;
    description?: (string | null);
    id: string;
    owner_id: string;
};

export type ItemsPublic = {
    data: Array<ItemPublic>;
    count: number;
};

export type ItemUpdate = {
    title?: (string | null);
    description?: (string | null);
};

export type Message = {
    message: string;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

export type QuestionCreate = {
    question_text: string;
    choices: Array<(string)>;
    correct_answers: Array<(string)>;
    subject: string;
    topic?: (string | null);
};

export type QuestionPublic = {
    question_text: string;
    choices: Array<(string)>;
    correct_answers: Array<(string)>;
    subject: string;
    topic?: (string | null);
    id: string;
    created_by: string;
    created_at: string;
    updated_at: string;
    subject_id: string;
    topic_id: (string | null);
};

export type QuestionsPublic = {
    data: Array<QuestionPublic>;
    count: number;
};

export type QuestionTemplateCreate = {
    subject: string;
    topic?: (string | null);
    difficulty: string;
    template_prompt: string;
    example_questions: Array<{
        [key: string]: unknown;
    }>;
    constraints?: {
        [key: string]: unknown;
    };
    is_active?: boolean;
};

export type QuestionTemplatePublic = {
    subject: string;
    topic?: (string | null);
    difficulty: string;
    template_prompt: string;
    example_questions: Array<{
        [key: string]: unknown;
    }>;
    constraints?: {
        [key: string]: unknown;
    };
    is_active?: boolean;
    id: string;
    created_by: (string | null);
    created_at: string;
    updated_at: string;
};

export type QuestionTemplatesPublic = {
    data: Array<QuestionTemplatePublic>;
    count: number;
};

export type QuestionTemplateUpdate = {
    subject?: (string | null);
    topic?: (string | null);
    difficulty?: (string | null);
    template_prompt?: (string | null);
    example_questions?: (Array<{
    [key: string]: unknown;
}> | null);
    constraints?: ({
    [key: string]: unknown;
} | null);
    is_active?: (boolean | null);
};

export type QuestionUpdate = {
    question_text?: (string | null);
    choices?: (Array<(string)> | null);
    correct_answers?: (Array<(string)> | null);
    subject?: (string | null);
    topic?: (string | null);
};

export type QuizAnswerSubmit = {
    question_id: string;
    selected_answers: Array<(string)>;
};

export type QuizAttemptPublic = {
    quiz_id: string;
    user_id: string;
    question_ids: Array<(string)>;
    user_answers?: {
        [key: string]: unknown;
    };
    score?: (number | null);
    total_questions: number;
    time_taken?: (number | null);
    started_at: string;
    completed_at?: (string | null);
    status?: string;
    id: string;
};

export type QuizAttemptsPublic = {
    data: Array<QuizAttemptPublic>;
    count: number;
};

export type QuizCreate = {
    subjects: Array<(string)>;
    topics?: (Array<(string)> | null);
    num_questions?: number;
    time_limit?: (number | null);
    is_timed?: boolean;
};

export type QuizPublic = {
    title: string;
    subjects: Array<(string)>;
    topics?: (Array<(string)> | null);
    num_questions?: number;
    time_limit?: (number | null);
    is_timed?: boolean;
    id: string;
    created_by: string;
    created_at: string;
};

export type QuizResultDetail = {
    question_id: string;
    question_text: string;
    choices: Array<(string)>;
    correct_answers: Array<(string)>;
    user_answers: Array<(string)>;
    is_correct: boolean;
    subject: string;
    topic: (string | null);
};

export type QuizResultPublic = {
    id: string;
    quiz_id: string;
    score: number;
    total_questions: number;
    percentage: number;
    time_taken: (number | null);
    started_at: string;
    completed_at: string;
    status: string;
    details: Array<QuizResultDetail>;
};

/**
 * Request model for rejecting a question.
 */
export type RejectQuestionRequest = {
    reason: string;
};

export type SubjectPublic = {
    name: string;
    id: string;
};

export type SubjectsPublic = {
    data: Array<SubjectPublic>;
    count: number;
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type TopicPublic = {
    name: string;
    id: string;
};

export type TopicsPublic = {
    data: Array<TopicPublic>;
    count: number;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    is_teacher?: boolean;
    full_name?: (string | null);
    password: string;
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    is_teacher?: boolean;
    full_name?: (string | null);
    id: string;
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    is_teacher?: boolean;
    full_name?: (string | null);
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type FeatureFlagsListFeatureFlagsForUserData = {
    limit?: number;
    skip?: number;
};

export type FeatureFlagsListFeatureFlagsForUserResponse = (FeatureFlagsPublic);

export type FeatureFlagsListAllFeatureFlagsData = {
    limit?: number;
    skip?: number;
};

export type FeatureFlagsListAllFeatureFlagsResponse = (FeatureFlagsPublic);

export type FeatureFlagsUpdateFlagData = {
    flagKey: string;
    requestBody: FeatureFlagUpdate;
};

export type FeatureFlagsUpdateFlagResponse = (FeatureFlagPublic);

export type FeatureFlagsCheckFlagStatusData = {
    flagKey: string;
};

export type FeatureFlagsCheckFlagStatusResponse = ({
    [key: string]: unknown;
});

export type ItemsReadItemsData = {
    limit?: number;
    skip?: number;
};

export type ItemsReadItemsResponse = (ItemsPublic);

export type ItemsCreateItemData = {
    requestBody: ItemCreate;
};

export type ItemsCreateItemResponse = (ItemPublic);

export type ItemsReadItemData = {
    id: string;
};

export type ItemsReadItemResponse = (ItemPublic);

export type ItemsUpdateItemData = {
    id: string;
    requestBody: ItemUpdate;
};

export type ItemsUpdateItemResponse = (ItemPublic);

export type ItemsDeleteItemData = {
    id: string;
};

export type ItemsDeleteItemResponse = (Message);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type MultiplayerGameCreateGameData = {
    requestBody: CardGameSessionCreate;
};

export type MultiplayerGameCreateGameResponse = (CardGameCreateResponse);

export type MultiplayerGameJoinGameData = {
    roomCode: string;
};

export type MultiplayerGameJoinGameResponse = (CardGameJoinResponse);

export type MultiplayerGameGetGameData = {
    gameId: string;
};

export type MultiplayerGameGetGameResponse = (CardGameSessionWithPlayers);

export type MultiplayerGameGetActiveGameResponse = ((CardGameSessionWithPlayers | null));

export type MultiplayerGameGetGameStateData = {
    gameId: string;
};

export type MultiplayerGameGetGameStateResponse = (CardGameStatePublic);

export type MultiplayerGameMarkReadyData = {
    gameId: string;
    ready?: boolean;
};

export type MultiplayerGameMarkReadyResponse = ({
    [key: string]: unknown;
});

export type MultiplayerGameGetPlayerHandData = {
    gameId: string;
};

export type MultiplayerGameGetPlayerHandResponse = (Array<{
    [key: string]: unknown;
}>);

export type MultiplayerGamePlayCardData = {
    gameId: string;
    requestBody: CardGameAnswerCreate;
};

export type MultiplayerGamePlayCardResponse = (CardGameAnswerResponse);

export type MultiplayerGameSkipTurnData = {
    gameId: string;
};

export type MultiplayerGameSkipTurnResponse = ({
    [key: string]: unknown;
});

export type MultiplayerGameGetGameResultsData = {
    gameId: string;
};

export type MultiplayerGameGetGameResultsResponse = (CardGameResultsResponse);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type QuestionGenerationGenerateQuestionsData = {
    requestBody: GenerateQuestionRequest;
};

export type QuestionGenerationGenerateQuestionsResponse = (GenerateQuestionResponse);

export type QuestionGenerationListGeneratedQuestionsData = {
    batchId?: (string | null);
    limit?: number;
    minScore?: (number | null);
    skip?: number;
    status?: (string | null);
};

export type QuestionGenerationListGeneratedQuestionsResponse = (GeneratedQuestionsPublic);

export type QuestionGenerationApproveGeneratedQuestionData = {
    questionId: string;
};

export type QuestionGenerationApproveGeneratedQuestionResponse = (QuestionPublic);

export type QuestionGenerationRejectGeneratedQuestionData = {
    questionId: string;
    requestBody: RejectQuestionRequest;
};

export type QuestionGenerationRejectGeneratedQuestionResponse = (Message);

export type QuestionGenerationApproveBatchData = {
    batchId: string;
};

export type QuestionGenerationApproveBatchResponse = (unknown);

export type QuestionsReadQuestionsData = {
    limit?: number;
    skip?: number;
    subject?: (string | null);
    topic?: (string | null);
};

export type QuestionsReadQuestionsResponse = (QuestionsPublic);

export type QuestionsCreateQuestionData = {
    requestBody: QuestionCreate;
};

export type QuestionsCreateQuestionResponse = (QuestionPublic);

export type QuestionsReadQuestionData = {
    id: string;
};

export type QuestionsReadQuestionResponse = (QuestionPublic);

export type QuestionsUpdateQuestionData = {
    id: string;
    requestBody: QuestionUpdate;
};

export type QuestionsUpdateQuestionResponse = (QuestionPublic);

export type QuestionsDeleteQuestionData = {
    id: string;
};

export type QuestionsDeleteQuestionResponse = (Message);

export type QuestionTemplatesListTemplatesData = {
    difficulty?: (string | null);
    isActive?: boolean;
    limit?: number;
    skip?: number;
    subject?: (string | null);
};

export type QuestionTemplatesListTemplatesResponse = (QuestionTemplatesPublic);

export type QuestionTemplatesCreateTemplateData = {
    requestBody: QuestionTemplateCreate;
};

export type QuestionTemplatesCreateTemplateResponse = (QuestionTemplatePublic);

export type QuestionTemplatesGetTemplateData = {
    templateId: string;
};

export type QuestionTemplatesGetTemplateResponse = (QuestionTemplatePublic);

export type QuestionTemplatesUpdateTemplateData = {
    requestBody: QuestionTemplateUpdate;
    templateId: string;
};

export type QuestionTemplatesUpdateTemplateResponse = (QuestionTemplatePublic);

export type QuestionTemplatesDeleteTemplateData = {
    templateId: string;
};

export type QuestionTemplatesDeleteTemplateResponse = (Message);

export type QuizzesStartQuizData = {
    requestBody: QuizCreate;
};

export type QuizzesStartQuizResponse = (QuizAttemptPublic);

export type QuizzesGetAttemptData = {
    attemptId: string;
};

export type QuizzesGetAttemptResponse = (QuizAttemptPublic);

export type QuizzesGetQuizDetailsData = {
    quizId: string;
};

export type QuizzesGetQuizDetailsResponse = (QuizPublic);

export type QuizzesSubmitAnswerData = {
    attemptId: string;
    requestBody: QuizAnswerSubmit;
};

export type QuizzesSubmitAnswerResponse = ({
    [key: string]: (string);
});

export type QuizzesCompleteQuizData = {
    attemptId: string;
};

export type QuizzesCompleteQuizResponse = (QuizResultPublic);

export type QuizzesGetQuizResultsData = {
    attemptId: string;
};

export type QuizzesGetQuizResultsResponse = (QuizResultPublic);

export type QuizzesGetQuizHistoryData = {
    limit?: number;
    skip?: number;
};

export type QuizzesGetQuizHistoryResponse = (QuizAttemptsPublic);

export type SubjectsReadSubjectsData = {
    limit?: number;
    skip?: number;
};

export type SubjectsReadSubjectsResponse = (SubjectsPublic);

export type TopicsReadTopicsData = {
    limit?: number;
    skip?: number;
};

export type TopicsReadTopicsResponse = (TopicsPublic);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);