const LIGHT_BROWN = "#fde2ae"
const DARK_BROWN = "#c6681e"
const DISCONNECTED_GRAY = "#9ca3af"
const SHIELD_GREY_BLUE = "#6A89A7"
const SHIELD_BLUE = "#38bdf8"
const SHIELD_BLUE_DARKER = "#2951f2"
const CARD_COLOR_DAMAGE = "#dc2626"
const CARD_COLOR_SHIELD = "#2563eb"
const CARD_COLOR_HEAL = "#16a34a"
const CARD_BACKGROUND_PLAYABLE_TOP_GRADIENT = "#fef5e0"
const CARD_BACKGROUND_PLAYABLE_BOTTOM_GRADIENT = "#e8d3ae"
const CARD_BACKGROUND_UNPLAYABLE_TOP_GRADIENT = "#fffbf0"
const CARD_BACKGROUND_UNPLAYABLE_BOTTOM_GRADIENT = "#f0dcb8"

// Question Popup colors (match card gradient)
const QUESTION_POPUP_TOP_GRADIENT = CARD_BACKGROUND_PLAYABLE_TOP_GRADIENT
const QUESTION_POPUP_BOTTOM_GRADIENT = CARD_BACKGROUND_PLAYABLE_BOTTOM_GRADIENT
const QUESTION_POPUP_BORDER = "#c4a47a" // Matches Card3D border
const QUESTION_POPUP_BOLD_TEXT = DARK_BROWN // For emphasized text
const QUESTION_POPUP_TITLE = DARK_BROWN // For title text

export const COLORS = {
  LIGHT_BROWN,
  DARK_BROWN,
  DISCONNECTED_GRAY,
  SHIELD_GREY_BLUE,
  SHIELD_BLUE,
  SHIELD_BLUE_DARKER,
  CARD_COLOR_DAMAGE,
  CARD_COLOR_SHIELD,
  CARD_COLOR_HEAL,
  CARD_BACKGROUND_PLAYABLE_TOP_GRADIENT,
  CARD_BACKGROUND_PLAYABLE_BOTTOM_GRADIENT,
  CARD_BACKGROUND_UNPLAYABLE_TOP_GRADIENT,
  CARD_BACKGROUND_UNPLAYABLE_BOTTOM_GRADIENT,
  QUESTION_POPUP_TOP_GRADIENT,
  QUESTION_POPUP_BOTTOM_GRADIENT,
  QUESTION_POPUP_BORDER,
  QUESTION_POPUP_BOLD_TEXT,
  QUESTION_POPUP_TITLE,
} as const
