"""Replace game models with card game models

Revision ID: 0b9c3a65a7e0
Revises: 83175ed0aea2
Create Date: 2025-12-04 15:23:08.868082

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0b9c3a65a7e0'
down_revision = '83175ed0aea2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cardtemplate',
    sa.Column('card_key', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('card_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('effect_data', sa.JSON(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cardtemplate_card_key'), 'cardtemplate', ['card_key'], unique=True)
    op.create_table('decktemplate',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('card_entries', sa.JSON(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_decktemplate_name'), 'decktemplate', ['name'], unique=True)
    op.create_table('cardgamesession',
    sa.Column('room_code', sqlmodel.sql.sqltypes.AutoString(length=6), nullable=False),
    sa.Column('subjects', sa.JSON(), nullable=True),
    sa.Column('topics', sa.JSON(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('host_ready', sa.Boolean(), nullable=False),
    sa.Column('guest_ready', sa.Boolean(), nullable=False),
    sa.Column('host_health', sa.Integer(), nullable=False),
    sa.Column('guest_health', sa.Integer(), nullable=False),
    sa.Column('host_shield', sa.Integer(), nullable=False),
    sa.Column('guest_shield', sa.Integer(), nullable=False),
    sa.Column('max_health', sa.Integer(), nullable=False),
    sa.Column('host_hand', sa.JSON(), nullable=True),
    sa.Column('guest_hand', sa.JSON(), nullable=True),
    sa.Column('deck', sa.JSON(), nullable=True),
    sa.Column('discard_pile', sa.JSON(), nullable=True),
    sa.Column('current_turn', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('turn_number', sa.Integer(), nullable=False),
    sa.Column('fatigue_damage', sa.Integer(), nullable=False),
    sa.Column('winner', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('host_id', sa.Uuid(), nullable=False),
    sa.Column('guest_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['guest_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['host_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cardgamesession_room_code'), 'cardgamesession', ['room_code'], unique=True)
    op.create_table('cardgameanswer',
    sa.Column('turn_number', sa.Integer(), nullable=False),
    sa.Column('card_played', sa.JSON(), nullable=True),
    sa.Column('selected_answers', sa.JSON(), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('effect_value', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('game_session_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('question_id', sa.Uuid(), nullable=False),
    sa.Column('answered_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['game_session_id'], ['cardgamesession.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('gameanswer')
    op.drop_index(op.f('ix_gamesession_room_code'), table_name='gamesession')
    op.drop_table('gamesession')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gameanswer',
    sa.Column('question_index', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('selected_answers', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('is_correct', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('game_session_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('question_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('answered_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['game_session_id'], ['gamesession.id'], name=op.f('gameanswer_game_session_id_fkey')),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], name=op.f('gameanswer_question_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('gameanswer_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('gameanswer_pkey'))
    )
    op.create_table('gamesession',
    sa.Column('room_code', sa.VARCHAR(length=6), autoincrement=False, nullable=False),
    sa.Column('subjects', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('topics', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('question_ids', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('current_question_index', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('host_ready', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('guest_ready', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('host_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('guest_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('started_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['guest_id'], ['user.id'], name=op.f('gamesession_guest_id_fkey')),
    sa.ForeignKeyConstraint(['host_id'], ['user.id'], name=op.f('gamesession_host_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('gamesession_pkey'))
    )
    op.create_index(op.f('ix_gamesession_room_code'), 'gamesession', ['room_code'], unique=True)
    op.drop_table('cardgameanswer')
    op.drop_index(op.f('ix_cardgamesession_room_code'), table_name='cardgamesession')
    op.drop_table('cardgamesession')
    op.drop_index(op.f('ix_decktemplate_name'), table_name='decktemplate')
    op.drop_table('decktemplate')
    op.drop_index(op.f('ix_cardtemplate_card_key'), table_name='cardtemplate')
    op.drop_table('cardtemplate')
    # ### end Alembic commands ###
