"""add end_reason to card_game_session

Revision ID: 48fdc374cfb5
Revises: 0b9c3a65a7e0
Create Date: 2025-12-30 21:44:05.533050

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '48fdc374cfb5'
down_revision = '0b9c3a65a7e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cardgamesession', sa.Column('end_reason', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cardgamesession', 'end_reason')
    # ### end Alembic commands ###
