"""Add special ability fields to CardGameSession

Revision ID: 7f68ccf37b64
Revises: 0a3b9785f837
Create Date: 2026-01-02 01:58:13.588470

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '7f68ccf37b64'
down_revision = '0a3b9785f837'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cardgamesession', sa.Column('host_ability_cooldown', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('cardgamesession', sa.Column('guest_ability_cooldown', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('cardgamesession', sa.Column('host_ability_active', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('cardgamesession', sa.Column('guest_ability_active', sa.Boolean(), nullable=False, server_default='false'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cardgamesession', 'guest_ability_active')
    op.drop_column('cardgamesession', 'host_ability_active')
    op.drop_column('cardgamesession', 'guest_ability_cooldown')
    op.drop_column('cardgamesession', 'host_ability_cooldown')
    # ### end Alembic commands ###
