/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RecoverPasswordRouteImport } from './routes/recover-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as GameRouteImport } from './routes/game'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutAdminRouteImport } from './routes/_layout/admin'
import { Route as LayoutQuizStartRouteImport } from './routes/_layout/quiz/start'
import { Route as LayoutGameCreateRouteImport } from './routes/_layout/game/create'
import { Route as LayoutAdminQuestionsRouteImport } from './routes/_layout/admin/questions'
import { Route as LayoutAdminFeatureFlagsRouteImport } from './routes/_layout/admin/feature-flags'
import { Route as LayoutAdminAiGenerateRouteImport } from './routes/_layout/admin/ai-generate'
import { Route as LayoutQuizTakeAttemptIdRouteImport } from './routes/_layout/quiz/take.$attemptId'
import { Route as LayoutQuizResultsAttemptIdRouteImport } from './routes/_layout/quiz/results.$attemptId'
import { Route as LayoutGameResultsGameIdRouteImport } from './routes/_layout/game/results.$gameId'
import { Route as LayoutGamePlayGameIdRouteImport } from './routes/_layout/game/play.$gameId'
import { Route as LayoutGameLobbyGameIdRouteImport } from './routes/_layout/game/lobby.$gameId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverPasswordRoute = RecoverPasswordRouteImport.update({
  id: '/recover-password',
  path: '/recover-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GameRoute = GameRouteImport.update({
  id: '/game',
  path: '/game',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminRoute = LayoutAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutQuizStartRoute = LayoutQuizStartRouteImport.update({
  id: '/quiz/start',
  path: '/quiz/start',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutGameCreateRoute = LayoutGameCreateRouteImport.update({
  id: '/game/create',
  path: '/game/create',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminQuestionsRoute = LayoutAdminQuestionsRouteImport.update({
  id: '/questions',
  path: '/questions',
  getParentRoute: () => LayoutAdminRoute,
} as any)
const LayoutAdminFeatureFlagsRoute = LayoutAdminFeatureFlagsRouteImport.update({
  id: '/feature-flags',
  path: '/feature-flags',
  getParentRoute: () => LayoutAdminRoute,
} as any)
const LayoutAdminAiGenerateRoute = LayoutAdminAiGenerateRouteImport.update({
  id: '/ai-generate',
  path: '/ai-generate',
  getParentRoute: () => LayoutAdminRoute,
} as any)
const LayoutQuizTakeAttemptIdRoute = LayoutQuizTakeAttemptIdRouteImport.update({
  id: '/quiz/take/$attemptId',
  path: '/quiz/take/$attemptId',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutQuizResultsAttemptIdRoute =
  LayoutQuizResultsAttemptIdRouteImport.update({
    id: '/quiz/results/$attemptId',
    path: '/quiz/results/$attemptId',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutGameResultsGameIdRoute = LayoutGameResultsGameIdRouteImport.update({
  id: '/game/results/$gameId',
  path: '/game/results/$gameId',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutGamePlayGameIdRoute = LayoutGamePlayGameIdRouteImport.update({
  id: '/game/play/$gameId',
  path: '/game/play/$gameId',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutGameLobbyGameIdRoute = LayoutGameLobbyGameIdRouteImport.update({
  id: '/game/lobby/$gameId',
  path: '/game/lobby/$gameId',
  getParentRoute: () => LayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/game': typeof GameRoute
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRouteWithChildren
  '/settings': typeof LayoutSettingsRoute
  '/': typeof LayoutIndexRoute
  '/admin/ai-generate': typeof LayoutAdminAiGenerateRoute
  '/admin/feature-flags': typeof LayoutAdminFeatureFlagsRoute
  '/admin/questions': typeof LayoutAdminQuestionsRoute
  '/game/create': typeof LayoutGameCreateRoute
  '/quiz/start': typeof LayoutQuizStartRoute
  '/game/lobby/$gameId': typeof LayoutGameLobbyGameIdRoute
  '/game/play/$gameId': typeof LayoutGamePlayGameIdRoute
  '/game/results/$gameId': typeof LayoutGameResultsGameIdRoute
  '/quiz/results/$attemptId': typeof LayoutQuizResultsAttemptIdRoute
  '/quiz/take/$attemptId': typeof LayoutQuizTakeAttemptIdRoute
}
export interface FileRoutesByTo {
  '/game': typeof GameRoute
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRouteWithChildren
  '/settings': typeof LayoutSettingsRoute
  '/': typeof LayoutIndexRoute
  '/admin/ai-generate': typeof LayoutAdminAiGenerateRoute
  '/admin/feature-flags': typeof LayoutAdminFeatureFlagsRoute
  '/admin/questions': typeof LayoutAdminQuestionsRoute
  '/game/create': typeof LayoutGameCreateRoute
  '/quiz/start': typeof LayoutQuizStartRoute
  '/game/lobby/$gameId': typeof LayoutGameLobbyGameIdRoute
  '/game/play/$gameId': typeof LayoutGamePlayGameIdRoute
  '/game/results/$gameId': typeof LayoutGameResultsGameIdRoute
  '/quiz/results/$attemptId': typeof LayoutQuizResultsAttemptIdRoute
  '/quiz/take/$attemptId': typeof LayoutQuizTakeAttemptIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/game': typeof GameRoute
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_layout/admin': typeof LayoutAdminRouteWithChildren
  '/_layout/settings': typeof LayoutSettingsRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/admin/ai-generate': typeof LayoutAdminAiGenerateRoute
  '/_layout/admin/feature-flags': typeof LayoutAdminFeatureFlagsRoute
  '/_layout/admin/questions': typeof LayoutAdminQuestionsRoute
  '/_layout/game/create': typeof LayoutGameCreateRoute
  '/_layout/quiz/start': typeof LayoutQuizStartRoute
  '/_layout/game/lobby/$gameId': typeof LayoutGameLobbyGameIdRoute
  '/_layout/game/play/$gameId': typeof LayoutGamePlayGameIdRoute
  '/_layout/game/results/$gameId': typeof LayoutGameResultsGameIdRoute
  '/_layout/quiz/results/$attemptId': typeof LayoutQuizResultsAttemptIdRoute
  '/_layout/quiz/take/$attemptId': typeof LayoutQuizTakeAttemptIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/game'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/settings'
    | '/'
    | '/admin/ai-generate'
    | '/admin/feature-flags'
    | '/admin/questions'
    | '/game/create'
    | '/quiz/start'
    | '/game/lobby/$gameId'
    | '/game/play/$gameId'
    | '/game/results/$gameId'
    | '/quiz/results/$attemptId'
    | '/quiz/take/$attemptId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/game'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/settings'
    | '/'
    | '/admin/ai-generate'
    | '/admin/feature-flags'
    | '/admin/questions'
    | '/game/create'
    | '/quiz/start'
    | '/game/lobby/$gameId'
    | '/game/play/$gameId'
    | '/game/results/$gameId'
    | '/quiz/results/$attemptId'
    | '/quiz/take/$attemptId'
  id:
    | '__root__'
    | '/_layout'
    | '/game'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/_layout/admin'
    | '/_layout/settings'
    | '/_layout/'
    | '/_layout/admin/ai-generate'
    | '/_layout/admin/feature-flags'
    | '/_layout/admin/questions'
    | '/_layout/game/create'
    | '/_layout/quiz/start'
    | '/_layout/game/lobby/$gameId'
    | '/_layout/game/play/$gameId'
    | '/_layout/game/results/$gameId'
    | '/_layout/quiz/results/$attemptId'
    | '/_layout/quiz/take/$attemptId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  GameRoute: typeof GameRoute
  LoginRoute: typeof LoginRoute
  RecoverPasswordRoute: typeof RecoverPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover-password': {
      id: '/recover-password'
      path: '/recover-password'
      fullPath: '/recover-password'
      preLoaderRoute: typeof RecoverPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game': {
      id: '/game'
      path: '/game'
      fullPath: '/game'
      preLoaderRoute: typeof GameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin': {
      id: '/_layout/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof LayoutAdminRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/quiz/start': {
      id: '/_layout/quiz/start'
      path: '/quiz/start'
      fullPath: '/quiz/start'
      preLoaderRoute: typeof LayoutQuizStartRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/game/create': {
      id: '/_layout/game/create'
      path: '/game/create'
      fullPath: '/game/create'
      preLoaderRoute: typeof LayoutGameCreateRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin/questions': {
      id: '/_layout/admin/questions'
      path: '/questions'
      fullPath: '/admin/questions'
      preLoaderRoute: typeof LayoutAdminQuestionsRouteImport
      parentRoute: typeof LayoutAdminRoute
    }
    '/_layout/admin/feature-flags': {
      id: '/_layout/admin/feature-flags'
      path: '/feature-flags'
      fullPath: '/admin/feature-flags'
      preLoaderRoute: typeof LayoutAdminFeatureFlagsRouteImport
      parentRoute: typeof LayoutAdminRoute
    }
    '/_layout/admin/ai-generate': {
      id: '/_layout/admin/ai-generate'
      path: '/ai-generate'
      fullPath: '/admin/ai-generate'
      preLoaderRoute: typeof LayoutAdminAiGenerateRouteImport
      parentRoute: typeof LayoutAdminRoute
    }
    '/_layout/quiz/take/$attemptId': {
      id: '/_layout/quiz/take/$attemptId'
      path: '/quiz/take/$attemptId'
      fullPath: '/quiz/take/$attemptId'
      preLoaderRoute: typeof LayoutQuizTakeAttemptIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/quiz/results/$attemptId': {
      id: '/_layout/quiz/results/$attemptId'
      path: '/quiz/results/$attemptId'
      fullPath: '/quiz/results/$attemptId'
      preLoaderRoute: typeof LayoutQuizResultsAttemptIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/game/results/$gameId': {
      id: '/_layout/game/results/$gameId'
      path: '/game/results/$gameId'
      fullPath: '/game/results/$gameId'
      preLoaderRoute: typeof LayoutGameResultsGameIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/game/play/$gameId': {
      id: '/_layout/game/play/$gameId'
      path: '/game/play/$gameId'
      fullPath: '/game/play/$gameId'
      preLoaderRoute: typeof LayoutGamePlayGameIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/game/lobby/$gameId': {
      id: '/_layout/game/lobby/$gameId'
      path: '/game/lobby/$gameId'
      fullPath: '/game/lobby/$gameId'
      preLoaderRoute: typeof LayoutGameLobbyGameIdRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutAdminRouteChildren {
  LayoutAdminAiGenerateRoute: typeof LayoutAdminAiGenerateRoute
  LayoutAdminFeatureFlagsRoute: typeof LayoutAdminFeatureFlagsRoute
  LayoutAdminQuestionsRoute: typeof LayoutAdminQuestionsRoute
}

const LayoutAdminRouteChildren: LayoutAdminRouteChildren = {
  LayoutAdminAiGenerateRoute: LayoutAdminAiGenerateRoute,
  LayoutAdminFeatureFlagsRoute: LayoutAdminFeatureFlagsRoute,
  LayoutAdminQuestionsRoute: LayoutAdminQuestionsRoute,
}

const LayoutAdminRouteWithChildren = LayoutAdminRoute._addFileChildren(
  LayoutAdminRouteChildren,
)

interface LayoutRouteChildren {
  LayoutAdminRoute: typeof LayoutAdminRouteWithChildren
  LayoutSettingsRoute: typeof LayoutSettingsRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutGameCreateRoute: typeof LayoutGameCreateRoute
  LayoutQuizStartRoute: typeof LayoutQuizStartRoute
  LayoutGameLobbyGameIdRoute: typeof LayoutGameLobbyGameIdRoute
  LayoutGamePlayGameIdRoute: typeof LayoutGamePlayGameIdRoute
  LayoutGameResultsGameIdRoute: typeof LayoutGameResultsGameIdRoute
  LayoutQuizResultsAttemptIdRoute: typeof LayoutQuizResultsAttemptIdRoute
  LayoutQuizTakeAttemptIdRoute: typeof LayoutQuizTakeAttemptIdRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAdminRoute: LayoutAdminRouteWithChildren,
  LayoutSettingsRoute: LayoutSettingsRoute,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutGameCreateRoute: LayoutGameCreateRoute,
  LayoutQuizStartRoute: LayoutQuizStartRoute,
  LayoutGameLobbyGameIdRoute: LayoutGameLobbyGameIdRoute,
  LayoutGamePlayGameIdRoute: LayoutGamePlayGameIdRoute,
  LayoutGameResultsGameIdRoute: LayoutGameResultsGameIdRoute,
  LayoutQuizResultsAttemptIdRoute: LayoutQuizResultsAttemptIdRoute,
  LayoutQuizTakeAttemptIdRoute: LayoutQuizTakeAttemptIdRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  GameRoute: GameRoute,
  LoginRoute: LoginRoute,
  RecoverPasswordRoute: RecoverPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
